# Generated by Django 3.1.4 on 2022-11-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date/Time')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('mid', models.IntegerField(verbose_name='$@MID@$')),
                ('action_type', models.IntegerField(choices=[(1, 'Deployed'), (2, 'Bottom'), (3, 'Recovered'), (4, 'Aborted'), (5, 'Attempted Comms'), (6, 'Release'), (7, 'On Deck'), (8, 'In Water'), (9, 'Start Deployment'), (10, 'On Bottom'), (999, 'Other')], verbose_name='Event Type')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_number', models.IntegerField(verbose_name='Bottle Number')),
                ('date_time', models.DateTimeField(verbose_name='Fired Date/Time')),
            ],
        ),
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Field Name')),
                ('label', models.CharField(max_length=30, verbose_name='Column Label')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('file_type', models.IntegerField(choices=[(1, '.LOG'), (2, '.BTL')], verbose_name='File Type')),
                ('processed', models.BooleanField(default=True, verbose_name='Processed')),
            ],
        ),
        migrations.CreateModel(
            name='DataFileDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.FilePathField(allow_files=False, allow_folders=True, verbose_name='File Directory')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(verbose_name='Event ID')),
                ('sample_id', models.IntegerField(blank=True, null=True, verbose_name='Sample ID')),
                ('end_sample_id', models.IntegerField(blank=True, null=True, verbose_name='End Sample ID')),
            ],
            options={
                'ordering': ('event_id',),
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Mission Name')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Field Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Field Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Field Value')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_variables', to='core.action', verbose_name='Action')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_variables', to='core.variablename', verbose_name='Field Name')),
            ],
        ),
        migrations.CreateModel(
            name='LogError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('line', models.IntegerField(verbose_name='Line #')),
                ('stack_trace', models.TextField(verbose_name='Stack Trace')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_errors', to='core.datafile', verbose_name='Log File')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Instrument Name')),
                ('instrument_type', models.IntegerField(choices=[(1, 'CTD'), (2, 'RingNet'), (3, 'Mooring'), (4, 'Viking Buoy'), (5, 'VPR'), (999, 'Other')], verbose_name='Instrument Type')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instrument', to='core.event', verbose_name='Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='event',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.station', verbose_name='Station'),
        ),
        migrations.CreateModel(
            name='DataFileDirectoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.IntegerField(choices=[(1, '.LOG'), (2, '.BTL')], verbose_name='File Types')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_types', to='core.datafiledirectory', verbose_name='Directory')),
            ],
        ),
        migrations.AddField(
            model_name='datafiledirectory',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_directories', to='core.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='core.datafiledirectory', verbose_name='Directoy'),
        ),
        migrations.CreateModel(
            name='BottleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Value')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottle_data', to='core.bottle', verbose_name='Bottle')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottle_data', to='core.datacolumn', verbose_name='Column Heading')),
            ],
        ),
        migrations.AddField(
            model_name='bottle',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to='core.event', verbose_name='Event'),
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Attachment Name')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.instrument', verbose_name='Instrument')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='action',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.datafile', verbose_name='File'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_id', 'mission')},
        ),
    ]
