# Generated by Django 3.1.4 on 2022-11-17 13:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date/Time')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('mid', models.IntegerField(verbose_name='$@MID@$')),
                ('action_type', models.IntegerField(choices=[(1, 'Deployed'), (2, 'Bottom'), (3, 'Recovered'), (4, 'Aborted'), (5, 'Attempted Comms'), (6, 'Release'), (7, 'On Deck'), (8, 'In Water'), (9, 'Start Deployment'), (10, 'On Bottom'), (999, 'Other')], verbose_name='Event Type')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Fired Date/Time')),
                ('bottle_id', models.IntegerField(verbose_name='Bottle ID')),
                ('bottle_number', models.IntegerField(verbose_name='Bottle Number')),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('file_type', models.IntegerField(choices=[(1, '.LOG'), (2, '.BTL')], verbose_name='File Type')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
            ],
        ),
        migrations.CreateModel(
            name='DataFileDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.FilePathField(allow_files=False, allow_folders=True, verbose_name='File Directory')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(verbose_name='Event ID')),
                ('sample_id', models.IntegerField(blank=True, null=True, verbose_name='Sample ID')),
                ('end_sample_id', models.IntegerField(blank=True, null=True, verbose_name='End Sample ID')),
            ],
            options={
                'ordering': ('event_id',),
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Instrument Name')),
                ('instrument_type', models.IntegerField(choices=[(1, 'CTD'), (2, 'RingNet'), (3, 'Mooring'), (4, 'Viking Buoy'), (5, 'VPR'), (999, 'Other')], verbose_name='Instrument Type')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Mission Name')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Field Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Field Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Field Value')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_variables', to='core.action', verbose_name='Action')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_variables', to='core.variablename', verbose_name='Field Name')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Sensor Name')),
                ('sensor_type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Pressure'), (2, 'Temperature'), (3, 'Salinity'), (4, 'Oxygen'), (5, 'Sigma-é'), (6, 'Time'), (7, 'Conductivity'), (8, 'Ph'), (9, 'Chlorophyll'), (10, 'CStarAt'), (11, 'Altimeter'), (12, 'Par'), (13, 'CDOM'), (99, 'other')], default=0, verbose_name='Sensor Type')),
                ('priority', models.IntegerField(default=1, help_text='1 = primary sensor, 2 = secondary sensor, 3 = tertiary, etc.', verbose_name='Priority')),
                ('units', models.CharField(blank=True, max_length=10, null=True, verbose_name='Units')),
            ],
            options={
                'unique_together': {('name', 'priority', 'units')},
            },
        ),
        migrations.CreateModel(
            name='SaltSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('sample_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sample Date')),
                ('sample_id', models.CharField(default='', max_length=50, verbose_name='Sample ID')),
                ('calculated_salinity', models.FloatField(verbose_name='Calculated Salinity')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salt_data', to='core.bottle', verbose_name='Bottle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OxygenSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('winkler_1', models.FloatField(verbose_name='Winkler 1')),
                ('winkler_2', models.FloatField(blank=True, null=True, verbose_name='Winkler 2')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxygen_data', to='core.bottle', verbose_name='Bottle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstrumentSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Attachment Name')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.event', verbose_name='Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.instrument', verbose_name='Instrument'),
        ),
        migrations.AddField(
            model_name='event',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='event',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.station', verbose_name='Station'),
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(max_length=50, verbose_name='file')),
                ('error_code', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing Sample ID'), (2, 'Bad Sample ID'), (3, 'Missing Information')], default=0, verbose_name='Error Code')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('stack_trace', models.TextField(verbose_name='Stack Trace')),
                ('line', models.IntegerField(verbose_name='Line/Object #')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_errors', to='core.datafile', verbose_name='Log File')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_errors', to='core.mission', verbose_name='mission')),
            ],
        ),
        migrations.CreateModel(
            name='DataFileDirectoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.IntegerField(choices=[(1, '.LOG'), (2, '.BTL')], verbose_name='File Types')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_types', to='core.datafiledirectory', verbose_name='Directory')),
            ],
        ),
        migrations.AddField(
            model_name='datafiledirectory',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_directories', to='core.mission', verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_files', to='core.datafiledirectory', verbose_name='Directoy'),
        ),
        migrations.CreateModel(
            name='CTDData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Value')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottle_data', to='core.bottle', verbose_name='Bottle')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottle_data', to='core.sensor', verbose_name='Column Heading')),
            ],
        ),
        migrations.AddField(
            model_name='bottle',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottles', to='core.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='action',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='action',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actions', to='core.datafile', verbose_name='File'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_id', 'mission')},
        ),
        migrations.CreateModel(
            name='ChlSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('sample_order', models.IntegerField(verbose_name='Sample Order')),
                ('chl', models.FloatField(verbose_name='CHL')),
                ('phae', models.FloatField(verbose_name='PHAE')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chl_data', to='core.bottle', verbose_name='Bottle')),
            ],
            options={
                'unique_together': {('bottle', 'sample_order')},
            },
        ),
    ]
