# Generated by Django 3.1.4 on 2022-11-15 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chlsample',
            name='file',
            field=models.FileField(default='na.csv', upload_to='', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oxygensample',
            name='file',
            field=models.FileField(default='na.csv', upload_to='', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saltsample',
            name='file',
            field=models.FileField(default='na.csv', upload_to='', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saltsample',
            name='sample_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 11, 55, 15, 774047, tzinfo=utc), verbose_name='Sample Date'),
        ),
    ]
