# Generated by Django 3.1.4 on 2022-11-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_type_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Action Other'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.IntegerField(choices=[(1, 'Deployed'), (2, 'Bottom'), (3, 'Recovered'), (4, 'Aborted'), (5, 'Attempted Comms'), (6, 'Release'), (7, 'On Deck'), (8, 'In Water'), (9, 'Start Deployment'), (10, 'On Bottom'), (999, 'Other')], verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Pressure'), (2, 'Temperature'), (3, 'Salinity'), (4, 'Oxygen'), (5, 'Sigma-é'), (6, 'Time'), (7, 'Conductivity'), (8, 'Ph'), (9, 'Fluorescence'), (10, 'CStarAt'), (11, 'Altimeter'), (12, 'Par'), (99, 'other')], default=0, verbose_name='Sensor Type'),
        ),
    ]
