# Generated by Django 3.1.4 on 2022-11-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaltSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(default='', max_length=50, verbose_name='Sample ID')),
                ('calculated_salinity', models.FloatField(verbose_name='Calculated Salinity')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salt_data', to='core.bottle', verbose_name='Bottle')),
            ],
        ),
    ]
