# Generated by Django 3.1.4 on 2022-11-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221124_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='error_code',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Missing Sample ID'), (2, 'Bad Sample ID'), (3, 'Missing Information'), (4, 'Duplicate Value')], default=0, verbose_name='Error Code'),
        ),
    ]
