# Generated by Django 4.1.3 on 2022-12-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_action_action_type_other_bottle_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='logged',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.IntegerField(choices=[(1, 'Deployed'), (2, 'Bottom'), (3, 'Recovered'), (4, 'Aborted'), (5, 'Attempted Comms'), (6, 'Release'), (7, 'On Deck'), (8, 'In Water'), (9, 'Start Deployment'), (10, 'On Bottom'), (11, 'Started'), (999, 'Other')], verbose_name='Action Type'),
        ),
        migrations.CreateModel(
            name='ElogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(default='Action', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_action', to='core.variablename')),
                ('attached', models.ForeignKey(default='Attached', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_attached', to='core.variablename')),
                ('comment', models.ForeignKey(default='Comment', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_comment', to='core.variablename')),
                ('end_sample_id', models.ForeignKey(default='End_Sample_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_end_sample_id', to='core.variablename')),
                ('event', models.ForeignKey(default='Event', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_event', to='core.variablename')),
                ('instrument', models.ForeignKey(default='Instrument', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_instrument', to='core.variablename')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elog_config', to='core.mission')),
                ('start_sample_id', models.ForeignKey(default='Sample ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_start_sample_id', to='core.variablename')),
                ('station', models.ForeignKey(default='Station', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_station', to='core.variablename')),
                ('time_position', models.ForeignKey(default='Time|Position', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_time_position', to='core.variablename')),
            ],
        ),
        migrations.CreateModel(
            name='ChnSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('sample_order', models.IntegerField(verbose_name='Sample Order')),
                ('volume', models.FloatField(default=-1.0, verbose_name='Volume(L)')),
                ('carbon', models.FloatField(default=-1.0, verbose_name='Carbon(ug/L)')),
                ('nitrogen', models.FloatField(default=-1.0, verbose_name='Nitrogen(ug/L)')),
                ('carbon_nitrogen', models.FloatField(default=-1.0, verbose_name='Carbon/Nitrogen')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chn_data', to='core.bottle', verbose_name='Bottle')),
            ],
            options={
                'unique_together': {('bottle', 'sample_order')},
            },
        ),
    ]
