# Generated by Django 4.1.3 on 2022-12-14 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_action_action_type_other_bottle_pressure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.OneToOneField(default='Action', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_action', to='core.variablename')),
                ('attached', models.OneToOneField(default='Attached', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_attached', to='core.variablename')),
                ('comment', models.OneToOneField(default='Comment', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_comment', to='core.variablename')),
                ('end_sample_id', models.OneToOneField(default='End_Sample_ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_end_sample_id', to='core.variablename')),
                ('event', models.OneToOneField(default='Event', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_event', to='core.variablename')),
                ('instrument', models.OneToOneField(default='Instrument', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_instrument', to='core.variablename')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elog_config', to='core.mission')),
                ('start_sample_id', models.OneToOneField(default='Sample ID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_start_sample_id', to='core.variablename')),
                ('station', models.OneToOneField(default='Station', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_station', to='core.variablename')),
                ('time_position', models.OneToOneField(default='Time|Position', on_delete=django.db.models.deletion.DO_NOTHING, related_name='elog_time_position', to='core.variablename')),
            ],
        ),
    ]
