# Generated by Django 3.1.4 on 2022-11-03 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_saltsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='saltsample',
            name='sample_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 12, 42, 35, 28003, tzinfo=utc), verbose_name='Sample Date'),
        ),
    ]
