# Generated by Django 3.1.4 on 2022-11-03 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_saltsample_sample_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saltsample',
            name='sample_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 13, 52, 57, 362962, tzinfo=utc), verbose_name='Sample Date'),
        ),
        migrations.CreateModel(
            name='ChlSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_order', models.IntegerField(verbose_name='Sample Order')),
                ('chl', models.FloatField(verbose_name='CHL')),
                ('phae', models.FloatField(verbose_name='PHAE')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chl_data', to='core.bottle', verbose_name='Bottle')),
            ],
            options={
                'unique_together': {('bottle', 'sample_order')},
            },
        ),
    ]
