# Generated by Django 4.1.3 on 2022-12-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_error_logged_alter_action_action_type_elogconfig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chnsample',
            name='volume',
        ),
    ]
