# Generated by Django 4.1.3 on 2022-12-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_elogconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.IntegerField(choices=[(1, 'Deployed'), (2, 'Bottom'), (3, 'Recovered'), (4, 'Aborted'), (5, 'Attempted Comms'), (6, 'Release'), (7, 'On Deck'), (8, 'In Water'), (9, 'Start Deployment'), (10, 'On Bottom'), (11, 'Started'), (999, 'Other')], verbose_name='Action Type'),
        ),
    ]
