# Generated by Django 4.1.3 on 2022-12-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_chnsample_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='HplcSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('acarot', models.FloatField(blank=True, null=True, verbose_name='ACAROT')),
                ('allox', models.FloatField(blank=True, null=True, verbose_name='ALLOX')),
                ('astax', models.FloatField(blank=True, null=True, verbose_name='ASTAX')),
                ('bcarot', models.FloatField(blank=True, null=True, verbose_name='BCAROT')),
                ('but19', models.FloatField(blank=True, null=True, verbose_name='BUT19')),
                ('butlike', models.FloatField(blank=True, null=True, verbose_name='BUTLIKE')),
                ('chla', models.FloatField(blank=True, null=True, verbose_name='CHLA')),
                ('chlb', models.FloatField(blank=True, null=True, verbose_name='CHLB')),
                ('chlc12', models.FloatField(blank=True, null=True, verbose_name='CHLC12')),
                ('chlc3', models.FloatField(blank=True, null=True, verbose_name='CHLC3')),
                ('chlidea', models.FloatField(blank=True, null=True, verbose_name='CHLIDEA')),
                ('diadinox', models.FloatField(blank=True, null=True, verbose_name='DIADINOX')),
                ('diatox', models.FloatField(blank=True, null=True, verbose_name='DIATOX')),
                ('fucox', models.FloatField(blank=True, null=True, verbose_name='FUCOX')),
                ('hex19', models.FloatField(blank=True, null=True, verbose_name='HEX19')),
                ('hexlike', models.FloatField(blank=True, null=True, verbose_name='HEXLIKE')),
                ('hexlike2', models.FloatField(blank=True, null=True, verbose_name='HEXLIKE2')),
                ('perid', models.FloatField(blank=True, null=True, verbose_name='PERID')),
                ('phaeo', models.FloatField(blank=True, null=True, verbose_name='PHAEO')),
                ('prasinox', models.FloatField(blank=True, null=True, verbose_name='PRASINOX')),
                ('pyrophae', models.FloatField(blank=True, null=True, verbose_name='PYROPHAE')),
                ('violax', models.FloatField(blank=True, null=True, verbose_name='VIOLAX')),
                ('zea', models.FloatField(blank=True, null=True, verbose_name='ZEA')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hplc_data', to='core.bottle', verbose_name='Bottle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
