# Generated by Django 4.1.3 on 2022-12-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_action_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='logged',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
