# Generated by Django 4.1.3 on 2022-11-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bottle_pressure_alter_action_id_alter_bottle_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='bottle_id',
        ),
    ]
