# Generated by Django 4.1.3 on 2022-12-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_error_logged'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChnSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('sample_order', models.IntegerField(verbose_name='Sample Order')),
                ('volume', models.FloatField(default=-1.0, verbose_name='Volume(L)')),
                ('carbon', models.FloatField(default=-1.0, verbose_name='Carbon(ug/L)')),
                ('nitrogen', models.FloatField(default=-1.0, verbose_name='Nitrogen(ug/L)')),
                ('carbon_nitrogen', models.FloatField(default=-1.0, verbose_name='Carbon/Nitrogen')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chn_data', to='core.bottle', verbose_name='Bottle')),
            ],
            options={
                'unique_together': {('bottle', 'sample_order')},
            },
        ),
    ]
