# Generated by Django 4.1.3 on 2022-12-22 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_datafile_file_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=20, verbose_name='Column Name')),
                ('priority', models.IntegerField(default=1, help_text='1 = primary sensor, 2 = secondary sensor, 3 = tertiary, etc.', verbose_name='Priority')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='core.mission', verbose_name='Mission')),
            ],
        ),
        migrations.CreateModel(
            name='SensorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.IntegerField(choices=[(1, 'Pressure'), (2, 'Temperature'), (3, 'Salinity'), (4, 'Oxygen'), (5, 'Sigma-é'), (6, 'Time'), (7, 'Conductivity'), (8, 'Ph'), (9, 'Fluorescence'), (10, 'Beam Attenuation'), (11, 'Altimeter'), (12, 'Par'), (13, 'Turbidity'), (99, 'other')], default=99, verbose_name='Sensor Type')),
                ('sensor_type_other', models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Sensor Type')),
                ('units', models.CharField(blank=True, max_length=40, null=True, verbose_name='Units')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Other Information')),
            ],
        ),
        migrations.RemoveField(
            model_name='ctddata',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.AddField(
            model_name='missionsensor',
            name='sensor_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensors', to='core.sensordetails', verbose_name='Sensor Details'),
        ),
        migrations.AddField(
            model_name='ctddata',
            name='column_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottle_data', to='core.missionsensor', verbose_name='Sensor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='missionsensor',
            unique_together={('mission', 'column_name')},
        ),
    ]
