# Generated by Django 4.1.3 on 2022-12-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_missionsensor_sensordetails_remove_ctddata_sensor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctddata',
            old_name='column_name',
            new_name='sensor',
        ),
        migrations.AlterField(
            model_name='sensordetails',
            name='sensor_type',
            field=models.IntegerField(choices=[(1, 'Pressure'), (2, 'Temperature'), (3, 'Salinity'), (4, 'Oxygen'), (5, 'Sigma-é'), (6, 'Time'), (7, 'Conductivity'), (8, 'Ph'), (9, 'Fluorescence'), (10, 'Beam Attenuation'), (11, 'Altimeter'), (12, 'PAR/Logarithmic'), (13, 'Turbidity'), (14, 'SPAR/Surface Irradiance'), (99, 'other')], default=99, verbose_name='Sensor Type'),
        ),
    ]
