# Generated by Django 4.1.3 on 2022-12-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_column_name_ctddata_sensor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bottle',
            unique_together={('event', 'bottle_number')},
        ),
    ]
