# Generated by Django 4.2 on 2024-02-21 14:23
from django.core.management import call_command
from django.db import migrations, models


def load_defaults(apps, schema_editor):
    # add default limit fields for nutrients
    call_command('loaddata', 'default_settings_fixtures', ignorenonexistent=True)


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0006_globalstation_latitude_globalstation_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstation',
            name='fixstation',
            field=models.BooleanField(default=False, verbose_name='Fix Station'),
        ),
        migrations.RunPython(load_defaults, lambda x, y: None),
    ]
