# Generated by Django 4.2 on 2024-05-23 09:54
from django.core.management import call_command
from django.db import migrations, models


def load_defaults(apps, schema_editor):
    # add default limit fields for nutrients
    call_command('loaddata', 'file_configuration_defaults', ignorenonexistent=True)


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0007_globalstation_fixstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletypeconfig',
            name='limit_field',
            field=models.CharField(blank=True, help_text='Lowercase name of the column that contains flags, if it exists', max_length=50, null=True, verbose_name='Detection Limit Column'),
        ),
        migrations.RunPython(load_defaults, lambda x, y: None),
    ]
