# Generated by Django 4.2 on 2025-02-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsdb', '0010_globalsampletypecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalStationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(help_text='Nominal pressure data is collected for', verbose_name='Pressure')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='settingsdb.globalstation', verbose_name='Station Plan')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalStationAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collected', models.BooleanField(default=False, help_text='Is this collected at the nominal pressure?', verbose_name='Collected')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='settingsdb.globalsampletypecategory', verbose_name='Sample Type')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='settingsdb.globalstationplan', verbose_name='Station Plan')),
            ],
        ),
    ]
